### ISSUE TITLE
Crash, if some short-lived nodes connects to a cluster.

### ISSUE THREAD

**Issue by liveforeverx** [skirino/raft_fleet#6]
Crash, if some short-lived nodes connects to a cluster.

```elixir
2018-08-30 13:38:01.847 [error] Child RaftKV.WorkflowExecutor of Supervisor #PID<0.2539.0> (Supervisor.Default) terminated
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {["ap@ip": :ok], [:"remote_shell@ip"]}
        (raft_kv) lib/raft_kv/ets_record_manager.ex:79: RaftKV.EtsRecordManager.ensure_record_changed_in_all_relevant_nodes!/1
        (raft_kv) lib/raft_kv/workflow.ex:301: RaftKV.Workflow.execute/1
        (raft_kv) lib/raft_kv/workflow_executor.ex:22: RaftKV.WorkflowExecutor.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Do we really need to send update to all non raft `relevant` nodes?

**Comment by liveforeverx** [comment]
Sorry, issue should be in `raft_kv`
